vich_uploader:
    db_driver: orm

    mappings:
        movies:
            uri_prefix: /img/movies
            upload_destination: '%kernel.project_dir%/public/img/movies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
