# Dockerfile Moviz (déploiement sur Render)

# Étape 1 : Image de base PHP avec Alpine avec FPM
FROM php:8.3-fpm-alpine

# Étape 2 : Installation des dépendances système
RUN apk add --no-cache \
    nginx \
    bash \
    icu-dev \
    libxml2-dev \
    libzip-dev \
    unzip \
    git \
    curl

# Étape 3 : Installer les extensions PHP nécessaires
RUN docker-php-ext-install \
    zip \
    pdo \
    pdo_mysql \
    opcache \
    intl \
    bcmath

# Étape 4 : Nettoyer les fichiers temporaires
RUN rm -rf /tmp/* /var/cache/apk/*

# Étape 5 : Installe Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# Autoriser les plugins Composer
ENV COMPOSER_ALLOW_SUPERUSER=1

# Étape 7 : Définir le répertoire de travail
WORKDIR /var/www/html

# Étape 8 : Copier le projet dans le conteneur - 
COPY . .

ENV APP_ENV=prod

# Étape 9 : Installer les dépendances PHP avec Composer
RUN composer install --no-interaction --no-dev --optimize-autoloader \
    && php bin/console cache:warmup || true 

# Étape 10: Permissions
RUN mkdir -p var public \
    && chown -R www-data:www-data var public

# Étape 12 : Copier la configuration Nginx
COPY nginx/nginx.conf.template /etc/nginx/nginx.conf

# Étape 13 : Copier le script de démarrage
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Exposer le port 80 (for Render to detect traffic HTTP)
EXPOSE 80

# Commande de démarrage
CMD ["sh", "/start.sh"]
